### ISSUE TITLE
"Real" backup feature ? (historization)

### ISSUE THREAD

**Issue by kitatek** [OpenNebula/addon-image-backup#6]
Hi,

Very interested to try this, but ... I do not see neither in the doc nor in the code (1st time I read nodejs so I might be wrong) where to configure the number of historical copies to keep for an image.  

So I guess the backup process overwrites the only backup copy existing, defeating the purpose of backup that should allow you to restore from a, chosen, trusted, past copy.

This is where synchronization (you use rsync, right ?) differs from backup: the capability to keep multiple copies.

Could you please clarify in the doc that part of the features ?

Or best, allow to configure a number of past copies to keep ?

Thank you.

**Comment by feldsam** [comment]
Hello, yes, you are right, there is no history, but image is copied to tmp file and after check it is moved to right file, which efectively overwrites previos backup.

you can use this script in conjuction with other backup sw, for ex. borgbackup or bacula.

we don't use this script anymore because of moving to HPE 3PAR storage system, for which we developed custom DS/TM driver and backup script in python with use of borgbackup.

I have plan to extend our new python backup with support for qcow2 datastores and release it, but no deadline was set.

**Comment by kitatek** [comment]
Sounds great! 

Thanks for pointing to borgbackup that seems the right approach to backup a ONE cloud (thanks to dedup feature).

Looking forward to see your python script fo qcow2 files !
